### ISSUE TITLE
Post Commit Hook by Branch Name?

### ISSUE THREAD

**Issue by ilaif** [Spaceman-Labs/asana-post-commit#4]
I usually create a branch per task in Asana. A branch can have several commits and I don't want to include the task id in every commit.
An option to check the branch's name for a task id instead of the commit's comment would be great!

What do you think?

**Comment by joelkraut** [comment]
That's a great idea! I am excited to approve your pull request! =)

**Comment by ilaif** [comment]
I created the pull request :) Waiting to see what you think.

**Comment by loren138** [comment]
Just for documentation, this was closed by: https://github.com/Spaceman-Labs/asana-post-commit/pull/6
