### ISSUE TITLE
Reg: afplib second instance of FNN

### ISSUE THREAD

**Issue by rsundar90** [Spaceman-Labs/asana-post-commit#9]
Hi team,

We are unable to find the size/length  of the second instance of FNN in AFP file. we are using afplib API.
Please help resolve the same.

Implementation of Rg2 in api was left blank.
We tried the below snippet for obj.Rg2()  which didnt work out.
Please let us know first in place if we can edit the API. Is there any user manual for the afplib API.

if(obj.getRg2() != null && obj.getRg2().size() > 0) {
            int size1 = binary_triplets(buffer, start + 11, obj.getRg2());
            if(11 + size1 > length){ length = 11 + size1;}  
            }

**Comment by joelkraut** [comment]
Wrong repo?
